# Generated by Django 5.2.12 on 2026-03-18 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='archived_by_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='complaint',
            name='deleted_by_admin',
            field=models.BooleanField(default=False),
        ),
    ]
